// amrita-robotics/src/routes/about/+page.svelte
<script lang="ts">
  import Navbar from '$lib/Navbar.svelte';
  import Footer from '$lib/Footer.svelte';
</script>

<Navbar currentPage="about" />

<main class="section container glass about-section">
  <h1>About Amrita Robotics</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit...</p>
  <p>RoboCon achievements and lab info...</p>
  <p><strong>Past RoboCon:</strong> Add achievements here.</p>
</main>

<Footer />

<style>
.about-section {
	padding: 80px 20px;
	display: flex;
	flex-direction: column;
	gap: 1.5rem;
	text-align: center;
	max-width: 900px;
	margin: auto;
}
</style>

// src/app/about/page.jsx
export default function AboutPage() {
    return (
        <main className="section about-section">
            <div className="container card glass">
                <h1>About Amrita Robotics</h1>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vitae
                    justo vitae urna aliquet tincidunt. Integer aliquet, nibh nec malesuada
                    vulputate, augue mauris cursus ipsum, sed cursus orci libero id quam.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, RoboCon achievements and lab info can go
                    here. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices
                    posuere cubilia curae; Phasellus quis rutrum nulla.
                </p>
                <p>
                    <strong>Past RoboCon:</strong> Lorem ipsum dolor sit amet, consectetur
                    adipiscing elit. (Add your achievements here.)
                </p>
            </div>
        </main>
    );
}
